"""
QA loop module facade.

Provides QA validation loop functionality.
Re-exports from qa package for clean imports.
"""

from qa import (
    ISSUE_SIMILARITY_THRESHOLD,
    MAX_QA_ITERATIONS,
    RECURRING_ISSUE_THRESHOLD,
    _issue_similarity,
    _normalize_issue_key,
    check_test_discovery,
    create_manual_test_plan,
    escalate_to_human,
    get_iteration_history,
    get_qa_iteration_count,
    get_qa_signoff_status,
    get_recurring_issue_summary,
    has_recurring_issues,
    is_fixes_applied,
    is_no_test_project,
    is_qa_approved,
    is_qa_rejected,
    load_implementation_plan,
    load_qa_fixer_prompt,
    print_qa_status,
    record_iteration,
    run_qa_agent_session,
    run_qa_fixer_session,
    run_qa_validation_loop,
    save_implementation_plan,
    should_run_fixes,
    should_run_qa,
)

__all__ = [
    "MAX_QA_ITERATIONS",
    "RECURRING_ISSUE_THRESHOLD",
    "ISSUE_SIMILARITY_THRESHOLD",
    "run_qa_validation_loop",
    "load_implementation_plan",
    "save_implementation_plan",
    "get_qa_signoff_status",
    "is_qa_approved",
    "is_qa_rejected",
    "is_fixes_applied",
    "get_qa_iteration_count",
    "should_run_qa",
    "should_run_fixes",
    "print_qa_status",
    "get_iteration_history",
    "record_iteration",
    "has_recurring_issues",
    "get_recurring_issue_summary",
    "escalate_to_human",
    "create_manual_test_plan",
    "check_test_discovery",
    "is_no_test_project",
    "_normalize_issue_key",
    "_issue_similarity",
    "run_qa_agent_session",
    "load_qa_fixer_prompt",
    "run_qa_fixer_session",
]
