"""
Workspace management module facade.

Provides workspace setup and management utilities for isolated builds.
Re-exports from core.workspace for clean imports.
"""

from core.workspace import (
    MergeLock,
    MergeLockError,
    ParallelMergeResult,
    ParallelMergeTask,
    WorkspaceChoice,
    WorkspaceMode,
    check_existing_build,
    choose_workspace,
    cleanup_all_worktrees,
    copy_spec_to_worktree,
    create_conflict_file_with_git,
    discard_existing_build,
    finalize_workspace,
    get_changed_files_from_branch,
    get_current_branch,
    get_existing_build_worktree,
    get_file_content_from_ref,
    handle_workspace_choice,
    has_uncommitted_changes,
    is_binary_file,
    is_process_running,
    list_all_worktrees,
    merge_existing_build,
    print_conflict_info,
    print_merge_success,
    review_existing_build,
    setup_workspace,
    show_build_summary,
    show_changed_files,
    validate_merged_syntax,
)

__all__ = [
    "MergeLock",
    "MergeLockError",
    "ParallelMergeResult",
    "ParallelMergeTask",
    "WorkspaceChoice",
    "WorkspaceMode",
    "check_existing_build",
    "choose_workspace",
    "cleanup_all_worktrees",
    "copy_spec_to_worktree",
    "create_conflict_file_with_git",
    "discard_existing_build",
    "finalize_workspace",
    "get_changed_files_from_branch",
    "get_current_branch",
    "get_existing_build_worktree",
    "get_file_content_from_ref",
    "handle_workspace_choice",
    "has_uncommitted_changes",
    "is_binary_file",
    "is_process_running",
    "list_all_worktrees",
    "merge_existing_build",
    "print_conflict_info",
    "print_merge_success",
    "review_existing_build",
    "setup_workspace",
    "show_build_summary",
    "show_changed_files",
    "validate_merged_syntax",
]
